version: '3.8'

services:
  code_analysis:
    build: .
    container_name: code_analysis
    command: bash -c "uvicorn code_analysis_service.app.main:app --host 0.0.0.0 --port 8080 --log-level info"
    ports:
      - '8080:8080'
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env
    restart: always

  migration:
    build: .
    container_name: db_migration
    depends_on:
      - db
    command: bash -c "alembic -c alembic.ini upgrade head"
    volumes:
      - ./:/app
    env_file:
      - .env
    restart: "no"


  db:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - db.env
    volumes:
      - code_db:/var/lib/postgresql/data
    ports:
      - '5433:5432'

    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready' ]
      timeout: 1s
      retries: 3

  celery_worker:
    build: .
    container_name: code-analysis-celery
    command: celery -A code_analysis_service.app.config.celery.celery_app worker --loglevel=info -Q code_analysis_queue
    depends_on:
      - redis
    volumes:
      - ./:/app
    env_file:
      - .env

  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "6380:6379"
    restart: always

volumes:
  code_db:
