"""empty message

Revision ID: 7b7408211762
Revises: 62a8df8f8062
Create Date: 2025-03-17 11:49:18.247958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b7408211762'
down_revision: Union[str, None] = '62a8df8f8062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    job_status_enum = sa.Enum(
        'PENDING',
        'DOWNLOADING',
        'DONE',
        'FAILED',
        name='job_status_enum'
    )
    job_status_enum.create(op.get_bind())
    op.add_column('job', sa.Column('status', sa.Enum('PENDING', 'DOWNLOADING', 'DONE', 'FAILED', name='job_status_enum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'status')
    job_status_enum = sa.Enum(
        'PENDING',
        'DOWNLOADING',
        'DONE',
        'FAILED',
        name='job_status_enum'
    )
    job_status_enum.drop(op.get_bind())
    # ### end Alembic commands ###
